version: '3'
services:
        node:
                build: .

                tty: true
                environment:
                    - NODE_ENV=production
                volumes: 
                - ./:/usr/src/app
                ports:
                - "3000:3000"
                networks:
                 backend:
                  ipv4_address: 172.30.0.2
                container_name: node_react

networks:
 backend:
   external: true
