version: '3'
services:
        node:
                build: .
                tty: true
                environment:
                    - NODE_ENV=production
                volumes: 
                - ./:/usr/src/app
                ports:
                - "3000:3000"

